from pathlib import Path
from parallax.models.enter.web import RenderRequest
from datetime import datetime
from parallax.interfaces.enter.usecases import IRenderUseCase


class RenderService(IRenderUseCase):
    def __init__(self):
        pass

    def _timestamp(self) -> str:
        return datetime.now().strftime("%Y%m%d_%H%M%S")

    async def execute(self, request: RenderRequest) -> dict:
        output_dir = Path("/app/output")
        output_dir.mkdir(parents=True, exist_ok=True)

        file_path = output_dir / f"{request.filename}_{self._timestamp()}.html"

        cards = []
        for item in request.items:
            motives = "".join(
                f"<span style='display:inline-block;background:#1f2937;color:#e5e7eb;padding:4px 10px;border-radius:999px;margin:4px 6px 0 0;font-size:12px;'>{m}</span>"
                for m in item.motives
            )
            entities = "".join(
                f"<span style='display:inline-block;background:#0f172a;color:#cbd5e1;padding:4px 10px;border-radius:999px;margin:4px 6px 0 0;font-size:12px;border:1px solid #334155;'>{e}</span>"
                for e in item.key_entities
            )

            intensity = int(item.emotional_intensity * 100)

            bar = f"""
            <div style="width:100px;height:6px;background:#1f2937;border-radius:999px;overflow:hidden;margin-top:4px;">
                <div style="width:{intensity}%;height:100%;background:#3b82f6;"></div>
            </div>
            """

            cards.append(f"""
            <div style="background:linear-gradient(180deg,#111827 0%,#0f172a 100%);border:1px solid #1f2937;border-radius:18px;padding:18px;margin-bottom:16px;box-shadow:0 10px 30px rgba(0,0,0,0.25);">
                <div style="display:flex;justify-content:space-between;align-items:flex-start;gap:12px;">
                    <div>
                        <div style="font-size:20px;font-weight:700;color:#f8fafc;line-height:1.3;">
                            {item.headline}
                        </div>
                        <div style="margin-top:8px;font-size:13px;color:#94a3b8;">
                            Source: {item.source}
                        </div>
                    </div>
                    <div style="background:#1e3a8a;color:white;padding:6px 12px;border-radius:999px;font-size:12px;font-weight:700;white-space:nowrap;">
                        {item.stance}
                    </div>
                </div>

                <div style="margin-top:14px;font-size:14px;color:#cbd5e1;line-height:1.5;">
                    {item.narrative_summary}
                </div>

                <div style="display:flex;gap:24px;margin-top:16px;flex-wrap:wrap;">
                    <div>
                        <div style="font-size:12px;color:#64748b;">Tone</div>
                        <div style="font-size:15px;font-weight:600;color:#f8fafc;">{item.emotional_tone}</div>
                    </div>
                    <div>
                        <div style="font-size:12px;color:#64748b;">Intensity</div>
                        <div style="font-size:15px;font-weight:600;color:#f8fafc;">
                            {intensity}%
                        </div>
                        {bar}
                    </div>
                </div>

                <div style="margin-top:18px;">
                    <div style="font-size:12px;color:#64748b;margin-bottom:4px;">Entities</div>
                    <div>{entities}</div>
                </div>

                <div style="margin-top:14px;">
                    <div style="font-size:12px;color:#64748b;margin-bottom:4px;">Motives</div>
                    <div>{motives}</div>
                </div>

                <div style="margin-top:18px;">
                    <a href="{item.url}" target="_blank" style="color:#60a5fa;font-size:13px;text-decoration:none;">
                        Open source ↗
                    </a>
                </div>
            </div>
            """)

        html = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <title>{request.title}</title>
        </head>
        <body style="font-family:Inter,Arial,sans-serif;background:#020617;padding:32px;">
            <div style="max-width:1100px;margin:0 auto;">
                <h1 style="color:#f8fafc;font-size:32px;margin-bottom:8px;">{request.title}</h1>
                <p style="color:#94a3b8;margin-bottom:24px;">Generated by Parallax</p>
                {''.join(cards)}
            </div>
        </body>
        </html>
        """

        file_path.write_text(html, encoding="utf-8")

        return {
            "status": "saved",
            "path": str(file_path),
            "filename": request.filename,
        }